version: '3'

services:
  gitea:
    image: gitea/gitea
    container_name: gitea
    volumes:
      - ./volumes/gitea:/data    
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    networks:
      - ci-network
    ports:
       - '3000:3000'
       - '222:22'
    expose:
      - '3000'
    depends_on:
      - mysql  
      
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_ROOT_HOST='%'
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - ci-network
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - ./.docker/init-products.sql:/docker-entrypoint-initdb.d/init-products.sql
      - ./volumes/mysql:/var/lib/mysql
      
networks:
  ci-network:
    driver: bridge